### PR TITLE
Remove admin functionality and port to python3

### PR DESCRIPTION
**Pull request by Sohalt**

### CODE REVIEW

**Comment by arvoelke** [comment]
Thanks for the PR! The update to Python3 is much appreciated / useful. Might I ask why the admin code was removed? I found that quite helpful for debugging things on the server as a live game is running. If it's a security concern, perhaps the page could default to not being accessible. The password hash could be changed to the empty string, with clearer instructions for how to set it using `utils.hash_obj()`.

**Comment by Sohalt** [comment]
Yes, I removed the admin code because of a security concern.
It does not add anything that you would also get through a regular ssh shell, does it?
But feel free to drop that commit.

**Comment by arvoelke** [comment]
> It does not add anything that you would also get through a regular ssh shell, does it?

I don't think you could use a regular `ssh` shell to get these capabilities unless there is some sort of trick I'm missing. The admin page here lets you do things like inspect `self.application.users` or `self.application.games` as live code objects (print and even modify their values within the server instance). Back when this was being developed I found this quite useful for inspecting the state of the server and testing things as a game is running. Note that none of this state is persisted in files/databases; it is all held in memory (and thus wiped when the server is reset). If the code was rewritten to use a database then you would be right that a regular `ssh` shell would probably suffice.

**Comment by Sohalt** [comment]
Ah, sorry -- my bad. I confused Python's `exec` for the `exec` syscall. I can see why that would be useful.
Though I still think in it's current form it's a security issue. You should need to explicitly opt in to enable this feature (it came as a little bit of a bad surprise for me when I looked through the code to convert it to python3 and found what looked like a backdoor on first sight).
Speaking of security, I also think it would be a good idea to not execute the program as root and rather have it listen on an unprivileged port and use a reverse proxy (which then also could provide TLS).

**Comment by simonneutert** [comment]
@Sohalt arguments are worth discussing imho.

**Comment by arvoelke** [comment]
> @Sohalt arguments are worth discussing imho.

@simonneutert I did address the main point already in my initial reply (see "If it's a security concern, perhaps the page could default to not being accessible."). For some additional context, this is the first time anyone has indicated any interest in using this since it was published over 6 years ago. This hasn't exactly been coded with wide-spread use in mind -- it's only been a privately hosted server for light use between friends. And so I appreciate the patience in addressing this pull request.

@Sohalt 

Thanks for the contributions. I've merged in the Python 3 commit (2f4fdf6b1766311e5fb03a067927f1ce6f8263a3), and added several more commits which should address your remaining comments (and more):
 - Admin page is opt-in by default
 - Admin handler serves 404 if not opted in
 - New password must be generated for config.json
 - Default port changed from 80 -> 8888
 - Tornado debugging disabled by default
 - Removed suggestion to use `sudo`
 - Added some missing images

Let me know if you have any more issues/requests in setting this up.

**Comment by Sohalt** [comment]
Cool, thank you!

**Pull request closed without merging**
